services:
  backend-follow-up:
    build: ./demo/
    ports:
      - "8080:8080"
    networks:
        - pruebas-follow-up
  db-follow-up:
    image: postgres:latest
    container_name: pruebas-postgres-follow-up
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db 
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
    networks:
        - pruebas-follow-up
networks:
  pruebas-follow-up:
